# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20160730_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='point_image',
            field=models.CharField(default='', max_length=500, verbose_name='exterlan link to foto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='point_link',
            field=models.CharField(default='', max_length=500, verbose_name='exterlan link to details'),
            preserve_default=False,
        ),
    ]
