# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ufoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_name', models.CharField(max_length=200, verbose_name='text name foto')),
                ('foto_lan', models.DecimalField(decimal_places=10, max_digits=13, verbose_name='lan')),
                ('foto_lat', models.DecimalField(decimal_places=10, max_digits=13, verbose_name='lat')),
                ('foto_date', models.DateTimeField(verbose_name='add date')),
            ],
        ),
    ]
