# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ufoto',
            name='foto_lan',
        ),
        migrations.AddField(
            model_name='ufoto',
            name='foto_lon',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=13, verbose_name=b'lon'),
            preserve_default=False,
        ),
    ]
